---
title: "RTutorial"
author: "ACOTTIN"
date: "January 23, 2017"
output: html_document
---

# Introduction
##blablablablablablalablablabla
###blablablablablablalablablabla
####blablablablablablalablablabla
blablablablablablablablablablablablabla

```{r, echo=FALSE}
#load the data

ourdata <- read.csv("data/TutoriqlBoats.csv",header = TRUE,sep = ";")

#firstrows<-head(ourdata,5)
#first five rows and then the first 3 columns or more exactly column 1 to 3
firstrows2<-ourdata[1:5,1:3]
#make it nice looking
knitr::kable(firstrows2)

#first the line and then the columns
#firstrows3<-ourdata[1:5,c(1,4,10,11)]

```
let's now see the correlation of our comments
```{r, echo=FALSE}
colnames(firstrows2)<-substring(colnames(firstrows2),first=1,last=4)
#colnames(firstrows2)<-c("me","myself","and I")
#add a column manually
firstrows2<-cbind(firstrows2,1:nrow(firstrows2))
#overwrite the variable firstrows2 by firstrows2 plus an additional column!! this is incremental
colnames(firstrows2)[ncol(firstrows2)]<-"new"
mycorrelationnumbers = cor(firstrows2)
knitr::kable(mycorrelationnumbers)
```
##Apply

use of apply function
```{r, echo=FALSE}
tmp = t(apply(firstrows2,2,summary))
tmp
#2 is for colulns, 1 is for rows

```